sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t ajulibe/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajulibe/multi-docker  npm run test -- --coverage

after_success:
  #building the various images
  - docker build -t ajulibe/multi-client ./client
  - docker build-t ajulibe/multi-nginx ./nginx
  - docker build -t ajulibe/multi-server ./server
  - docker build -t ajulibe/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  #Take the images and push it to docker hub
  - docker push ajulibe/multi-client
  - docker push ajulibe/multi-nginx
  - docker push ajulibe/multi-server
  - docker push ajulibe/multi-worker
