language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t akachi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akachi/react-test  npm test -- --coverage

after_success:
  #building the various images
  #- docker build -t akachi/multi-client ./client
  - docker build-t akachi/multi-nginx ./nginx
  - docker build -t akachi/multi-server ./server
  - docker build -t akachi/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take the images and push it to docker hub
  - docker push akachi/multi-client
  - docker push akachi/multi-nginx
  - docker push akachi/multi-server
  - docker push akachi/multi-worker
