version: "3.8"
services:
  postgres:
    image: "postgres:12.3-alpine"
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: "redis:latest"
    #its supposed to be server not api
    #but we changed it to avoid comflicts while setting up nginx
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - api
      - client
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      #linking our server directory to our root app folder
      #specified in the Dockerfile.dev file
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGPASSWORD=password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
